# Generated by Django 4.1 on 2022-08-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_p_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_add_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
